const fs=require('node:fs'),assert=require('node:assert/strict'),{JSDOM}=require('jsdom');
const path=require('node:path').resolve(__dirname,'../..');
const dom=new JSDOM(fs.readFileSync(path+'/media_clarity/static/index.html','utf8'),{url:'http://127.0.0.1:8765',runScripts:'outside-only'});
const w=dom.window,d=w.document,video=d.getElementById('video'),dialog=d.getElementById('player-dialog');
const tracks=[{index:0,language:'eng',codec:'aac',title:'First',channels:2},{index:1,language:'jpn',codec:'aac',title:'<img src=x> 第二',channels:2}];
const item={id:'a',title:'two voices',duration:10,position:0,width:640,height:360,available:true,audio_index:0,audio_tracks:tracks};
let delayedPreferences=[],delayPreferences=true,preference={included:false,preference:"neutral",revision:0},pendingSave=null;
let captions=[{id:'a-caption',source:'supplied',audio_index:0}],pending=null,requests=[],jobs=[];
w.setTimeout=()=>1;w.clearTimeout=()=>{};
w.fetch=async(url,opts={})=>{
 requests.push({url,opts});let value;
 if(url==='/api/session')value={token:'test',diagnostics:{ffmpeg:true,ffprobe:true}};
 else if(url==='/api/library')value={items:[item]};
 else if(url==='/api/library/a')value={...item};
 else if(url.includes('/audio/'))return new Promise(resolve=>{pending=resolve;});
 else if(url.endsWith('/position'))value={position:JSON.parse(opts.body).position};
 else if(url.endsWith('/subtitles'))value={tracks:captions,jobs};
 else if(url.includes('/subtitle-jobs'))value={id:'job'};
 else if(url.endsWith('/preference')){if(opts.method==='PUT')return new Promise(resolve=>{pendingSave=resolve;});if(delayPreferences)return new Promise(resolve=>delayedPreferences.push(resolve));value=preference;}
 else throw Error(url);
 return {ok:true,json:async()=>value};
};
Object.defineProperty(video,'readyState',{get:()=>2});Object.defineProperty(video,'duration',{get:()=>10});
video.play=()=>Promise.resolve();video.pause=()=>video.dispatchEvent(new w.Event('pause'));video.load=()=>{video.currentTime=0;};
dialog.showModal=()=>dialog.open=true;dialog.close=()=>dialog.open=false;
const settle=()=>new Promise(r=>setImmediate(r));
function choose(index){d.getElementById('audio-select').value=String(index);d.getElementById('audio-select').dispatchEvent(new w.Event('change'));d.getElementById('audio-apply').click();}
(async()=>{
 w.eval(fs.readFileSync(path+'/media_clarity/static/app.js','utf8')+'\nglobalThis.qa={openPlayer,closePlayer,refreshSubtitles,get owner(){return activeItem;}};');await settle();
 await w.qa.openPlayer('a');await settle();video.dispatchEvent(new w.Event('loadedmetadata'));video.currentTime=3.25;
 assert.match(video.src,/audio_index=0$/);assert.equal(d.getElementById('subtitle-select').value,'a-caption');
 assert.equal(d.querySelector('#audio-select img'),null);assert(d.getElementById('audio-select').textContent.includes('<img src=x>'));
 choose(1);await settle();assert.match(video.src,/audio_index=0$/);assert(d.getElementById('audio-apply').disabled);
 pending({ok:false,json:async()=>({error:'media_timeout'})});await settle();
 assert.match(video.src,/audio_index=0$/);assert.match(d.getElementById('audio-state').textContent,/현재 재생은 유지/);
 choose(1);await settle();item.audio_index=1;pending({ok:true,json:async()=>({...item})});await settle();
 video.dispatchEvent(new w.Event('loadedmetadata'));await settle();
 assert.match(video.src,/audio_index=1$/);assert.equal(video.currentTime,3.25);
 delayPreferences=false;for(const resolve of delayedPreferences)resolve({ok:true,json:async()=>preference});await settle();
 assert.equal(d.getElementById('preference-controls').disabled,false,'audio switch rebinds pending preference read');
 assert.equal(d.getElementById('subtitle-select').value,'','different audio caption is not auto-selected');
 assert.equal(video.querySelectorAll('track').length,0);
 d.getElementById('subtitle-generate').click();await settle();assert(requests.some(r=>r.url==='/api/library/a/subtitle-jobs?audio_index=1'));
 captions=[{id:'b-caption',source:'generated',audio_index:1},...captions];await w.qa.refreshSubtitles(w.qa.owner);
 assert.equal(d.getElementById('subtitle-select').value,'b-caption','first matching generated track is selected');
 jobs=[{id:'job',state:'paused',audio_index:0}];await w.qa.refreshSubtitles(w.qa.owner);
 assert.match(d.getElementById('subtitle-brief').textContent,/오디오 1/);
 d.getElementById('subtitle-select').value='a-caption';d.getElementById('subtitle-select').dispatchEvent(new w.Event('change'));
 assert.match(d.getElementById('subtitle-notes').textContent,/현재 음성과 다를 수/);
 d.getElementById('preference-value').value='like';d.getElementById('preference-value').dispatchEvent(new w.Event('change'));await settle();
 choose(0);await settle();item.audio_index=0;pending({ok:true,json:async()=>({...item})});await settle();
 assert(d.getElementById('preference-controls').disabled,'audio switch waits for in-flight preference save');
 preference={included:false,preference:'like',revision:1};pendingSave({ok:true,json:async()=>preference});await settle();await settle();
 assert.equal(d.getElementById('preference-controls').disabled,false);assert.equal(d.getElementById('preference-value').value,'like');
 choose(1);await settle();await w.qa.closePlayer();pending({ok:true,json:async()=>({...item,audio_index:0})});await settle();
 assert.equal(dialog.open,false);assert.equal(video.getAttribute('src'),null,'late preparation cannot reopen a closed player');
 assert(requests.filter(r=>r.url.endsWith('/position')).every(r=>Number.isInteger(JSON.parse(r.opts.body).audio_index)));
 w.close();console.log('PASS audio DOM: pinned playback/job inputs, failure retry, position retention, caption matching, late-response isolation (mocked media/HTTP).');
})().catch(e=>{w.close();console.error(e);process.exit(1);});
