const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {JSDOM}=require('jsdom');
const repo=path.resolve(__dirname,'../..');
const dom=new JSDOM(fs.readFileSync(path.join(repo,'media_clarity/static/index.html'),'utf8'),{url:'http://127.0.0.1:8765',runScripts:'outside-only'});
const w=dom.window,d=w.document,video=d.getElementById('video'),dialog=d.getElementById('player-dialog');
const items=['a','b'].map(id=>({id,title:id,duration:20,position:0,width:320,height:180,available:true,thumbnail:false}));
let data={tracks:[],jobs:[]}, pendingA=null, delayA=false;const posts=[];
let modelResult={device:'cuda',selection:'default',state:'blocked',error:'model_cuda_unavailable'},modelBusy=false;
const timers=new Map();let counter=0;
w.setTimeout=(fn,ms)=>{timers.set(++counter,{fn,ms});return counter;};w.clearTimeout=id=>timers.delete(id);
w.fetch=async (url,options={})=>{
 if(options.method==='POST')posts.push(url);
 if(url==='/api/session')return {ok:true,json:async()=>({token:'fixture',diagnostics:{ffmpeg:true,ffprobe:true,models:{device:'cuda',selection:'default',state:'unchecked',error:null}}})};
 if(url==='/api/models/diagnostics')return {ok:!modelBusy,json:async()=>modelBusy?{error:'processing_worker_active'}:modelResult};
 if(url==='/api/library')return {ok:true,json:async()=>({items})};
 if(url.endsWith('/subtitles')){
  if(delayA&&url.includes('/a/'))await new Promise(resolve=>pendingA=resolve);
  return {ok:true,json:async()=>JSON.parse(JSON.stringify(data))};
 }
 return {ok:true,json:async()=>({...items.find(i=>url.split('/')[3]===i.id)})};
};
Object.defineProperty(video,'readyState',{get:()=>1});Object.defineProperty(video,'duration',{get:()=>20});
video.play=()=>Promise.resolve();video.pause=()=>{};video.load=()=>{};dialog.showModal=()=>dialog.open=true;dialog.close=()=>dialog.open=false;
w.eval(fs.readFileSync(path.join(repo,'media_clarity/static/app.js'),'utf8')+'\nglobalThis.qa={openPlayer,closePlayer,refreshSubtitles,owner:()=>activeItem};');
const settle=()=>new Promise(resolve=>setImmediate(resolve));
(async()=>{
 await settle();
 const check=d.getElementById('model-check'),modelState=d.getElementById('model-check-state');
 assert(d.getElementById('model-device').textContent.includes('NVIDIA GPU'));
 check.click();assert.equal(check.disabled,true);check.click();await settle();
 assert.equal(posts.filter(p=>p==='/api/models/diagnostics').length,1);
 assert(modelState.textContent.includes('CUDA용 PyTorch'));assert.equal(check.disabled,false);
 modelResult={device:'cpu',selection:'configured',state:'ready',error:null};check.click();await settle();
 assert(d.getElementById('model-device').textContent.includes('CPU'));assert(modelState.textContent.includes('기본 실행 환경을 확인'));
 modelBusy=true;check.click();await settle();assert(modelState.textContent.includes('일시정지'));assert.equal(check.disabled,false);
 await w.qa.openPlayer('a');await settle();
 assert.equal(video.querySelectorAll('track').length,0);
 data={tracks:[{id:'first',source:'supplied'}],jobs:[]};await w.qa.refreshSubtitles(w.qa.owner());
 const generate=d.getElementById('subtitle-generate');assert.equal(generate.hidden,false);assert.equal(generate.textContent,'새 자막 만들기');
 generate.click();await settle();assert(posts.includes('/api/library/a/subtitle-jobs/regenerate'));
 assert.equal(video.querySelector('track').getAttribute('src'),'/api/library/a/subtitles/first.vtt');
 const select=d.getElementById('subtitle-select');select.value='';select.dispatchEvent(new w.Event('change'));
 assert.equal(video.querySelectorAll('track').length,0);
 await w.qa.refreshSubtitles(w.qa.owner());assert.equal(video.querySelectorAll('track').length,0,'poll must preserve user opting out');
 select.value='first';select.dispatchEvent(new w.Event('change'));assert.equal(video.querySelectorAll('track').length,1);
 data={tracks:[{id:'second',source:'generated'},{id:'first',source:'supplied'}],jobs:[{id:'j',state:'running',stage:'translation',completed:1,total:2}]};
 await w.qa.refreshSubtitles(w.qa.owner());assert.equal(select.value,'first','keep chosen version');
 assert.equal(generate.hidden,true,'active preparation cannot launch another job');
 assert.equal(d.getElementById('subtitle-progress').value,50);assert.equal(d.getElementById('subtitle-pause').hidden,false);
 data.jobs[0].state='paused';await w.qa.refreshSubtitles(w.qa.owner());assert.equal(d.getElementById('subtitle-resume').hidden,false);assert.equal(d.getElementById('subtitle-pause').hidden,true);
 data.jobs[0].state='succeeded';data.tracks[0].fallback_count=2;await w.qa.refreshSubtitles(w.qa.owner());
 assert(select.options[1].textContent.includes('원문 2구간'));assert(d.getElementById('subtitle-state').textContent.includes('[원문]'));
 data.tracks[0].review_count=3;data.tracks[0].fast_count=2;
 data.tracks[1].import_notes={empty:1,outside:2,clipped:1,settings:1,reordered:true};
 await w.qa.refreshSubtitles(w.qa.owner());
 const notes=d.getElementById('subtitle-notes');
 assert(notes.textContent.includes('빈 자막 1개'));assert(notes.textContent.includes('영상 밖 자막 2개'));assert(!notes.textContent.includes('읽기 속도'));
 select.value='second';select.dispatchEvent(new w.Event('change'));
 assert(notes.textContent.includes('읽기 속도가 빠른 구간 2개'));assert(!notes.textContent.includes('빈 자막'));
 select.value='';select.dispatchEvent(new w.Event('change'));assert.equal(notes.hidden,true);
 select.value='first';select.dispatchEvent(new w.Event('change'));
 delayA=true;const old=w.qa.refreshSubtitles(w.qa.owner());await settle();await w.qa.closePlayer();await w.qa.openPlayer('b');await settle();
 const before=video.querySelector('track').getAttribute('src');pendingA();await old;
 assert.equal(video.querySelector('track').getAttribute('src'),before);assert(before.includes('/b/'));
 await w.qa.closePlayer();assert.equal(video.querySelectorAll('track').length,0);assert.equal([...timers.values()].filter(t=>t.ms===1500).length,0);
 console.log('PASS subtitle DOM: ready-track attachment, off/version preservation, progress/pause, late-response isolation, close cleanup (mocked media/HTTP).');dom.window.close();
})().catch(e=>{console.error(e);process.exitCode=1;dom.window.close();});
