const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {JSDOM}=require('jsdom');
const repo=path.resolve(__dirname,'../..');
const dom=new JSDOM(fs.readFileSync(path.join(repo,'media_clarity/static/index.html'),'utf8'),{url:'http://127.0.0.1:8765',runScripts:'outside-only'});
const w=dom.window,d=w.document,video=d.getElementById('video'),dialog=d.getElementById('player-dialog');
const query=d.getElementById('subtitle-query'),results=d.getElementById('subtitle-results'),status=d.getElementById('subtitle-search-status');
const items=['a','b'].map(id=>({id,title:id,duration:120,position:0,width:320,height:180,available:true,thumbnail:false}));
const requests=[],timers=new Map();let counter=0,ready=1,plays=0,scrolls=0;
w.setTimeout=(fn,ms)=>{timers.set(++counter,{fn,ms});return counter;};w.clearTimeout=id=>timers.delete(id);
w.fetch=async (url,options={})=>{
 if(url.endsWith('/caption-view'))return {ok:true,json:async()=>({...JSON.parse(options.body),revision:JSON.parse(options.body).revision+1})};
 requests.push({url,...options});
 if(url==='/api/session')return {ok:true,json:async()=>({token:'fixture',diagnostics:{ffmpeg:true,ffprobe:true}})};
 if(url==='/api/library')return {ok:true,json:async()=>({items})};
 if(url.split('?')[0].endsWith('/subtitles'))return {ok:true,json:async()=>({tracks:[{id:'one',source:'generated'},{id:'two',source:'supplied'}],jobs:[]})};
 const item=items.find(i=>url.split('/')[3]===i.id);
 return {ok:true,json:async()=>({...item,...(options.body?JSON.parse(options.body):{})})};
};
Object.defineProperty(video,'readyState',{get:()=>ready});Object.defineProperty(video,'duration',{get:()=>120});
Object.defineProperty(video,'textTracks',{value:new w.EventTarget()});
video.play=()=>{plays++;return Promise.resolve();};video.pause=()=>{};video.load=()=>{video.currentTime=0;};dialog.showModal=()=>dialog.open=true;dialog.close=()=>dialog.open=false;
video.scrollIntoView=()=>{scrolls++;};w.HTMLElement.prototype.scrollIntoView=function(){};
w.eval(fs.readFileSync(path.join(repo,'media_clarity/static/app.js'),'utf8')+'\nglobalThis.qa={openPlayer,closePlayer,subtitleSearchMatches,subtitleSearchText};');
const settle=()=>new Promise(resolve=>setImmediate(resolve));
function search(text){query.value=text;query.dispatchEvent(new w.Event('input'));for(const [id,t] of timers){if(t.ms===150){timers.delete(id);t.fn();}}}
function loaded(cues,beforeLoad=()=>{}){
 const track=video.querySelector('track');
 const nativeCues=cues.map(([start,text,end=start+.1])=>({startTime:start,endTime:end,getCueAsHTML:()=>{const fragment=d.createDocumentFragment();fragment.append(d.createTextNode(text));return fragment;}}));
 Object.defineProperty(track,'track',{value:{mode:'showing',get cues(){return this.mode==='disabled'?null:nativeCues;}}});
 beforeLoad(track);track.dispatchEvent(new w.Event('load'));return track;
}
function select(id){const s=d.getElementById('subtitle-select');s.value=id;s.dispatchEvent(new w.Event('change'));}
function saves(){return requests.filter(r=>r.method==='PUT');}
(async()=>{
 await settle();await w.qa.openPlayer('a');await settle();
 search('한글');assert.equal(results.children.length,0);assert.match(status.textContent,/불러오는 중/);
 const oldTrack=loaded([[2,'한글 대사'],[12.5,'<Enter> & ＡＢＣ'],[20,'두 번째 한글']]);
 assert.equal(results.children.length,2,'match decomposed Korean without sending a query');
 search('abc');assert.equal(results.children.length,1,'case/width normalization');
 assert.match(results.textContent,/<Enter> & ＡＢＣ/);assert.equal(results.querySelector('enter'),null,'render literal cue text');
 const button=results.querySelector('button'),before=saves().length,playsBefore=plays;
 ready=0;button.click();assert.equal(video.currentTime,0);assert.equal(saves().length,before);
 ready=1;button.click();assert.equal(video.currentTime,12.5);assert.equal(plays,playsBefore+1);assert.equal(saves().length,before,'do not save before seek completion');
 video.dispatchEvent(new w.Event('seeked'));await settle();assert.equal(JSON.parse(saves().at(-1).body).position,12.5);assert.match(saves().at(-1).url,/\/a\//);
 oldTrack.track.mode='disabled';video.currentTime=1;button.click();assert.equal(video.currentTime,1,'native Off rejects retained clicks before the change event');
 video.textTracks.dispatchEvent(new w.Event('change'));await settle();assert.equal(results.children.length,0);assert.match(status.textContent,/자막을 켜/);
 oldTrack.track.mode='showing';video.textTracks.dispatchEvent(new w.Event('change'));await settle();assert.equal(results.children.length,1);
 button.click();assert.equal(video.currentTime,1,'native off/on invalidates old callbacks');
 results.querySelector('button').click();assert.equal(video.currentTime,12.5);
 search('없는 문장');assert.equal(results.children.length,0);assert.match(status.textContent,/없습니다/);
 search('');assert.equal(results.children.length,0,'no unsolicited transcript on empty query');
 select('two');await settle();assert.equal(results.children.length,0);search('한글');
 const secondTrack=loaded(Array.from({length:115},(_,i)=>[i+1,`한글 ${i}`]));
 assert.equal(results.children.length,50);assert.match(status.textContent,/115개.*1–50/);
 const previous=d.getElementById('subtitle-page-previous'),next=d.getElementById('subtitle-page-next'),pages=d.getElementById('subtitle-pages');
 const beforePaging={time:video.currentTime,plays,writes:saves().length};
 assert.equal(previous.disabled,true);assert.equal(next.disabled,false);assert.equal(pages.hidden,false);
 const pageOneButton=results.querySelector('button');results.scrollTop=200;next.click();
 assert.equal(results.children.length,50);assert.match(status.textContent,/51–100/);assert.equal(results.scrollTop,0);
 assert.equal(d.activeElement,results.querySelector('button'),'keyboard paging moves focus to the new result group');
 pageOneButton.click();assert.equal(video.currentTime,beforePaging.time,'old pages cannot seek');
 next.click();assert.equal(results.children.length,15);assert.match(status.textContent,/101–115/);assert.equal(next.disabled,true);
 next.click();assert.equal(results.children.length,15,'last page cannot go out of bounds');
 assert.deepEqual({time:video.currentTime,plays,writes:saves().length},beforePaging,'paging does not play or save');
 results.querySelector('li:last-child button').click();assert.equal(video.currentTime,115,'last match is reachable');assert(scrolls>0,'selection returns the video into view');
 previous.click();assert.match(status.textContent,/51–100/);previous.click();assert.match(status.textContent,/1–50/);
 search('한글 114');assert.equal(results.children.length,1);assert.equal(pages.hidden,true);search('한글');assert.match(status.textContent,/1–50/);
 const oldQueryButton=results.querySelector('button');query.value='다른 검색';query.dispatchEvent(new w.Event('input'));
 oldQueryButton.click();assert.equal(video.currentTime,115,'a query edit invalidates clicks before debounce fires');
 search('한글');video.currentTime=12.5;
 const staleButton=results.querySelector('button');
 select('');await settle();assert.equal(results.children.length,0);assert.match(status.textContent,/선택해/);
 staleButton.click();assert.equal(video.currentTime,12.5,'off invalidates old result callbacks');
 select('one');await settle();oldTrack.dispatchEvent(new w.Event('load'));oldTrack.dispatchEvent(new w.Event('error'));
 assert.match(status.textContent,/불러오는 중/,'detached same-id track cannot overwrite the new load');
 const failing=video.querySelector('track');failing.dispatchEvent(new w.Event('error'));assert.match(status.textContent,/못했습니다/);
 select('two');await settle();loaded([[9,'한글\n  새\t버전 <literal>']]);search('  한글 새　버전  ');
 assert.equal(results.children.length,1,'line breaks, repeated whitespace and full-width spaces match a phrase');
 assert.match(results.textContent,/한글\n  새\t버전 <literal>/,'display keeps the original text and line breaks');
 assert.equal(results.querySelector('literal'),null);search('한글');const itemAButton=results.querySelector('button');
 d.getElementById('subtitle-search-panel').open=true;
 await w.qa.closePlayer();assert.equal(query.value,'');assert.equal(results.children.length,0);assert.equal(d.getElementById('subtitle-search-panel').open,false);
 await w.qa.openPlayer('b');await settle();loaded([[30,'다른 영상']]);search('다른');
 const currentResults=results.textContent,writeCount=saves().length;
 itemAButton.click();secondTrack.dispatchEvent(new w.Event('load'));secondTrack.dispatchEvent(new w.Event('error'));await settle();
 assert.equal(video.currentTime,0);assert.equal(saves().length,writeCount);assert.equal(results.textContent,currentResults,'old item cannot leak cues or seek/save the new item');
 select('two');await settle();search('대기');
 const waiting=loaded([[2,'대기 중인 자막']],track=>{track.track.mode='disabled';video.textTracks.dispatchEvent(new w.Event('change'));});await settle();
 assert.equal(waiting.track.mode,'disabled','load completion preserves native Off chosen during fetch');
 assert.equal(results.children.length,0);assert.match(status.textContent,/자막을 켜/);
 waiting.track.mode='showing';video.textTracks.dispatchEvent(new w.Event('change'));await settle();assert.equal(results.children.length,1);
 assert.equal(w.localStorage.length,0);assert.equal(w.sessionStorage.length,0);assert.equal(w.location.search,'');
 assert(!requests.some(r=>JSON.stringify(r).includes('한글')||JSON.stringify(r).includes('없는 문장')||JSON.stringify(r).includes('다른')),'search text never enters HTTP');
 // General adjacent-cue cases, independent of any previous model evaluation text.
 const matching=(rows,q)=>w.qa.subtitleSearchMatches(rows.map(([start,end,text])=>({start,end,text,searchText:w.qa.subtitleSearchText(text)})),w.qa.subtitleSearchText(q));
 assert.equal(matching([[1,2,'오늘은'],[2.5,3,'공원에 가요']],'오늘은 공원에').length,1);
 assert.equal(matching([[1,2,'今日は公'],[2,3,'園に行く']],'公園').length,1,'no-space display boundary');
 assert.equal(matching([[1,2,'ＡＢＣ'],[2,3,'한글']],'abc 한글').length,1);
 assert.equal(matching([[1,2,'오늘은'],[2.501,3,'공원에']],'오늘은 공원에').length,0,'longer pause');
 assert.equal(matching([[1,2,'오늘은'],[1.9,3,'공원에']],'오늘은 공원에').length,0,'overlapping speakers');
 assert.equal(matching([[1,2,'앞 문장'],[2,3,'공원에 가요']],'공원에').length,1,'no preceding duplicate for a single-cue hit');
 assert.equal(matching([[1,2,'공원에'],[2,3,'공원에']],'공원에').length,2,'distinct repeated occurrences remain');
 assert.equal(matching([[1,2,'하나'],[2,3,'둘'],[3,4,'셋']],'하나 둘 셋').length,0,'no unbounded joining');
 assert.equal(matching([[1,2,'공원 에 가요']],'공원에').length,0,'do not remove spaces inside cues');
 assert.equal(matching([[1,NaN,'오늘은'],[2,3,'공원에']],'오늘은 공원에').length,0);
 select('one');await settle();
 loaded([[10.5,'경계 <literal>',12.5],[12.7,'너머 문장',14.5],[15,'다른 대사',16]]);
 search('경계 <literal> 너머');assert.equal(results.children.length,1);
 assert.match(results.textContent,/경계 <literal>\n너머 문장/);assert.equal(results.querySelector('literal'),null);
 const joinedButton=results.querySelector('button'),writesBefore=saves().length;
 joinedButton.click();assert.equal(video.currentTime,10.5,'first adjusted native timestamp');
 assert.equal(saves().length,writesBefore,'wait for completed seek');
 video.dispatchEvent(new w.Event('seeked'));await settle();assert.equal(JSON.parse(saves().at(-1).body).position,10.5);
 query.value='다른 대사';query.dispatchEvent(new w.Event('input'));video.currentTime=30;
 joinedButton.click();assert.equal(video.currentTime,30,'cross-cue callbacks also expire on query change');
 assert(!requests.some(r=>JSON.stringify(r).includes('경계')||JSON.stringify(r).includes('너머')),'joined query/text never enters HTTP');
 await w.qa.closePlayer();assert.equal([...timers.values()].filter(t=>t.ms===150).length,0);
 console.log('PASS subtitle search DOM: Unicode/whitespace/literal text, 115 results in bounded pages, keyboard focus, stale query/page guards, seek persistence, Off/version/item isolation, no query egress/history (mocked media/HTTP).');dom.window.close();
})().catch(e=>{console.error(e);process.exitCode=1;dom.window.close();});
